name: Deploy to Linode on push

on:
  push:
    branches:
      - staging        # change to whatever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Execute remote SSH commands using SSH key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.SEMA_ID_RSA }}
        script: whoami
