name: Deploy to Linode on push

on:
  push:
    branches:
      - staging        # change to whatever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH
        run: |
          echo "${{ secrets.LINODE_SSH_KEY }}" > "./id_rsa"
          chmod 600 "./id_rsa"

      - name: Run deploy script on Linode
        run: |
          ssh -o StrictHostKeyChecking=yes -i "./id_rsa" "${{ vars.LINODE_USER }}@${{ vars.LINODE_HOST }}" "/home/deploy/deploy_myapp.sh"
